version: '3'
services:
  web:
    build:
      context: ./test-devops1-angular
      dockerfile: Dockerfile
    image: devopsspring.azurecr.io/web-app:latest
  api:
    build:
      context: ./test-devops1
      dockerfile: Dockerfile
    image: devopsspring.azurecr.io/api-app:latest