apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app-1
  template:
    metadata:
      labels:
        app: spring-boot-app-1
    spec:
      containers:
      - name: spring-boot-app-1
        image: devopsspring.azurecr.io/api-app:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret
