apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80  # Adjust the port if needed
      targetPort: 80  # Adjust the port if needed
  type: LoadBalancer  # Change to ClusterIP or NodePort as needed